=== Ixf2/XSD-XML-DTD---WeatherApp---JoanaRam-rez/information.dtd
<!-- ========== WEATHER OBSERVATION ========== -->
<!ELEMENT weather_observation (locations)>
<!ELEMENT locations (location+)>

<!ELEMENT location (city, lactitude, logintude, observation)>
<!ELEMENT observation (date, temperature, humidity, wind_speed, condition)>

<!ELEMENT date (#PCDATA)>
<!ELEMENT temperature (#PCDATA)>
<!ATTLIST temperature unit CDATA #REQUIRED>

<!ELEMENT humidity (#PCDATA)>
<!ELEMENT wind_speed (#PCDATA)>
<!ATTLIST wind_speed unit CDATA #REQUIRED>

<!ELEMENT condition (#PCDATA)>

<!-- ========== WEATHER ALERT ========== -->
<!ELEMENT weather_alert (alerts_infos, period)>
<!ELEMENT alerts_infos (alert_info+)>

<!ELEMENT alert_info (
    alert_id,
    generate_at,
    severity,
    type,
    description,
    affected_areas
)>

<!ELEMENT alert_id (#PCDATA)>
<!ELEMENT generate_at (#PCDATA)>
<!ELEMENT severity (#PCDATA)>
<!ELEMENT type (#PCDATA)>
<!ELEMENT description (#PCDATA)>

<!ELEMENT affected_areas (affected_area+)>
<!ELEMENT affected_area (city, lactitude, logintude)>

<!ELEMENT period (start, end)>
<!ELEMENT start (#PCDATA)>
<!ELEMENT end (#PCDATA)>

<!-- ========== COMMON ELEMENTS ========== -->
<!ELEMENT city (#PCDATA)>
<!ELEMENT lactitude (#PCDATA)>
<!ATTLIST lactitude cardinal-point CDATA #REQUIRED>

<!ELEMENT logintude (#PCDATA)>
<!ATTLIST logintude cardinal-point CDATA #REQUIRED>

<!-- * 0 o más veces -->
<!-- + 1 o más veces -->
<!-- ? 0 o una vez (optional) -->

=== Ixf2/XSD-XML-DTD---WeatherApp---JoanaRam-rez/weather-observation.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- <!DOCTYPE weather_observation SYSTEM "information.dtd"> -->
<weather_observation xmlns="https://www.w3schools.com"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="https://www.w3schools.com weather-schema.xsd">
    <locations>
        <location>
            <city>Las Palmas de G.C.</city>
            <lactitude cardinal-point="N">28.07</lactitude>
            <logintude cardinal-point="O">15.43</logintude>
            <observation>
                <date>2026-01-18 00:00:00</date>
                <temperature unit="celsius">17.1</temperature>
                <humidity>68</humidity>
                <wind_speed unit="km/h">32</wind_speed>
                <condition>Rain</condition>
            </observation>
        </location>
        <location>
            <city>Tenerife</city>
            <lactitude cardinal-point="N">28.16</lactitude>
            <logintude cardinal-point="O">16.36</logintude>
            <observation>
                <date>2026-01-18 00:00:00</date>
                <temperature unit="celsius">13.5</temperature>
                <humidity>77</humidity>
                <wind_speed unit="km/h">27</wind_speed>
                <condition></condition>
            </observation>
        </location>
    </locations>
</weather_observation>


<!-- xmlns="https://www.w3schools.com"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="https://www.w3schools.com weather-schema.xsd" -->

=== Ixf2/XSD-XML-DTD---WeatherApp---JoanaRam-rez/weather-alert.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- <!DOCTYPE weather_alert SYSTEM "information.dtd"> -->
<weather_alert xmlns="https://www.w3schools.com"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="https://www.w3schools.com weather-schema.xsd">
    <alerts_infos>
        <alert_info>
            <alert_id>ALERT-2026-001</alert_id>
            <generate_at>2026-01-19T00:00:00</generate_at>
            <severity>High</severity>
            <type> Strong Wind</type>
            <description>
                Aviso por rachas de viento superiores a 80 km/h que pueden afectar a
                infraestructuras y al tráfico marítimo.
            </description>
            <affected_areas>
                <affected_area>
                    <city>Las Palmas de G.C.</city>
                    <lactitude cardinal-point="N">28.07</lactitude>
                    <logintude cardinal-point="O">15.43</logintude>
                </affected_area>
            </affected_areas>
            <period>
                <start>2026-01-19T00:00:00</start>
                <end>2026-01-19T23:00:00</end>
            </period>
        </alert_info>
        <alert_info>
            <alert_id>ALERT-2026-001</alert_id>
            <generate_at>2026-01-19T00:00:00</generate_at>
            <severity>Moderate</severity>
            <type> Heavy rain</type>
            <description>
                Precipitaciones intensas localizadas que podrían provocar acumulaciones
                de agua en zonas bajas.
            </description>
            <affected_areas>
                <affected_area>
                    <city>Tenerife</city>
                    <lactitude cardinal-point="N">28.07</lactitude>
                    <logintude cardinal-point="O">16.43</logintude>
                </affected_area>
            </affected_areas>
        </alert_info>
    </alerts_infos>
</weather_alert>

<!-- xmlns="https://www.w3schools.com"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="https://www.w3schools.com weather-schema.xsd" -->
